export const products = [
  {
    id: "product-1",
    image: "/products/product1.png",
    category: "gadget accessories, Airbuds",
    name: "Apple AirPods 3rd generation with Charging Case",
    price: "$699.00",
    oldPrice: "$799.00",
    badge: "Best Seller",
      brand: "The Apple Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-2",
    image: "/products/product2.png",
    category: "gadget accessories",
    name: "Apple AirPods Max",
    price: "$699.00",
    oldPrice: "$768.90",
    badge: "Sale!",
      brand: "The Apple Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-3",
    image: "/products/product3.png",
    category: "gadget accessories, Cameras",
    name: "Canon EOS 250D 24.1MP Full HD WI-FI DSLR Camera with 18-55mm",
    price: "$750.00",
    oldPrice: "$810.00",
    badge: "Best Seller",
      brand: "Sony Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-4",
    image: "/products/product4.png",
    category: "gadget accessories",
    name: "HP Laptop, AMD Ryzen 5 5500U Processor",
    price: "$1,659.00",
    oldPrice: "$1,907.85",
    badge: "Best Seller",
      brand: "hp Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-5",
    image: "/products/product5.png",
    category: "gadget accessories",
    name: "Intel 13th Gen Core i9 13900KF Raptor Lake Processor",
    price: "$799.00",
    oldPrice: "$918.85",
    badge: "Sale!",
    brand: "Hi-Tech Limited",
    collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-6",
    image: "/products/product6.png",
    category: "gadget accessories, Airbuds",
    name: "JBL E55BT Wireless Bluetooth Headphone",
    price: "$599.00",
    oldPrice: "$699.00",
    badge: "Sale!",
      brand: "A4 Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-7",
    image: "/products/product7.png",
    category: "gadget accessories",
    name: "MacBook Pro M4 Max Chip 16-inch (14-core CPU, 32-core GPU)",
    price: "$129.00",
    oldPrice: "$159.00",
    badge: "Sale!",
      brand: "The Apple Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-8",
    image: "/products/product8.png",
    category: "gadget accessories",
    name: "Mpow - CHE2S On-Ear Headphone with Mic for Kids",
    price: "$89.00",
    oldPrice: "$109.00",
    badge: "Best Seller",
      brand: "Hi-Tech Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-9",
    image: "/products/product9.png",
    category: "gadget accessories",
    name: "Realme Note 60x (4/64GB)",
    price: "$249.00",
    oldPrice: "$299.00",
    badge: "Best Seller",
      brand: "Huawei Company",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },
  {
    id: "product-10",
    image: "/products/product10.png",
    category: "gadget accessories, Smartphones",
    name: "Samsung Galaxy S25 Ultra 5G 12/256GB",
    price: "$399.00",
    oldPrice: "$459.00",
    badge: "Best Seller",
      brand: "Hi-Tech Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
  },


  {
    id: "product-11",
  image: "/products/Appliances1.png",
  category: "Appliances, Television",
  name: "43″ Class TU7000 Series Crystal UHD 4K Smart TV",
  price: "$299.00",
  oldPrice: "$349.00",
  badge: "Best Seller",
      brand: "Sony Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-12",
  image: "/products/Appliances2.png",
  category: "Appliances",
  name: "Apple Mac Mini M4 Chip 16/512GB Silver (10C CPU 10C GPU)",
  price: "$399.00",
  oldPrice: "$459.00",
  badge: "Sale!",
      brand: "The Apple Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-13",
  image: "/products/Appliances3.png",
  category: "Appliances, Smart Watches",
  name: "Apple Watch Series 10",
  price: "$499.00",
  oldPrice: "$599.00",
  badge: "Best Seller",
      brand: "The Apple Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-14",
  image: "/products/Appliances4.png",
  category: "Appliances, Washing Machine",
  name: "Laundry Wash Machine Washer/Spinner Pump",
  price: "$249.00",
  oldPrice: "$299.00",
  badge: "Sale!",
      brand: "The Hitach Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-15",
  image: "/products/Appliances5.png",
  category: "Appliances, Air Conditioners",
  name: "Midea 1 Ton Non-Inverter AC",
  price: "$199.00",
  oldPrice: "$249.00",
  badge: "Best Seller",
      brand: "Hi-Tech Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-16",
  image: "/products/Appliances6.png",
  category: "Kitchen Appliances",
  name: "Panasonic MX-EX1081 1.35L Blender",
  price: "$349.00",
  oldPrice: "$399.00",
  badge: "Sale!",
      brand: "Sony Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-17",
  image: "/products/Appliances7.png",
  category: "Kitchen Appliances",
  name: "Philips NA221 4.2 Liter 1500 Watt Air Fryer",
  price: "$279.00",
  oldPrice: "$329.00",
  badge: "Best Seller",
      brand: "Sony Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-18",
  image: "/products/Appliances8.png",
  category: "Appliances, Air Conditioners",
  name: "High Performance Cooling Fan, 4-Pin, 1500 RPM",
  price: "$449.00",
  oldPrice: "$499.00",
  badge: "Sale!",
      brand: "Hi-Tech Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},


{
  id: "product-19",
  image: "/products/Refrigerator1.png",
  category: "Refrigerators",
  name: "Bottom Freezer Refrigerator Stainless Wide 10.8",
  price: "$599.00",
  oldPrice: "$699.00",
  badge: "Best Seller",
      brand: "The Hitachi Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
{
  id: "product-20",
  image: "/products/Refrigerator2.png",
  category: "Appliances, Refrigerators",
  name: "Energy Star Stainless Steel Compact Freezer",
  price: "$749.00",
  oldPrice: "$849.00",
  badge: "Sale!",
      brand: "The Hitachi Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},

{
   id: "product-21",
  image: "/products/others.png",
  category: "others",
  name: "Vitamix A3500 Brushed Stainless Blender",
  price: "$199.00",
  oldPrice: "$249.00",
  badge: "Sale",
      brand: "Sony Limited",
  collection: "2026",
  type: "gadget",
  stock: "Available",
},
];